# 01 - PDF Extraction and Text Cleaning

This notebook explains and demonstrates the first stage of the Manufacturing Maintenance RAG Assistant.

## Learning objectives

By the end, you should be able to explain:

- Why a RAG system needs machine-readable text instead of visual PDF pages
- Why source document and page metadata must be preserved
- How repeated headers, footers, page numbers, and broken line wrapping affect retrieval
- Why direct extraction is preferable to OCR for digitally generated PDFs
- Why the processed corpus is stored as JSON Lines (JSONL)

## Implementation map - where extraction happens

The reusable implementation is in `src/extract_text.py`. Open it beside this notebook and locate: `find_repeated_edge_lines()`, `clean_page_text()`, `extract_document()`, and `extract_corpus()`.

- `find_repeated_edge_lines()` learns recurring headers and footers from page edges.
- `clean_page_text()` contains the main normalization and removal rules.
- `extract_document()` reads one PDF and creates page records with raw and cleaned text.
- `extract_corpus()` processes all PDFs and writes `pages.jsonl` plus diagnostics.

These function names are the exact implementation checkpoints you should understand.

## Pipeline

```text
NIST PDF -> page-level extraction -> cleaning -> metadata -> pages.jsonl
```

We keep both `raw_text` and `cleaned_text`. Raw text supports debugging and traceability; cleaned text is used by later chunking and embedding steps.

In [1]:
from pathlib import Path
import json
import sys

import pandas as pd
from pypdf import PdfReader
try:
    from IPython.display import display
except ImportError:
    display = print

# Support execution from either the project root or the notebooks folder.
current_dir = Path.cwd().resolve()
project_root = current_dir.parent if current_dir.name == 'notebooks' else current_dir
sys.path.insert(0, str(project_root))

from src.extract_text import (
    clean_page_text,
    extract_corpus,
    find_repeated_edge_lines,
)

raw_dir = project_root / 'data' / 'raw'
processed_dir = project_root / 'data' / 'processed'
pdf_paths = sorted(raw_dir.glob('*.pdf'))

print(f'Project root: {project_root}')
print(f'PDF documents found: {len(pdf_paths)}')
for path in pdf_paths:
    print('-', path.name)

Project root: <USER_HOME>\Documents\ChatGPT\Data Analytics\engineering-document-rag-assistant
PDF documents found: 3
- NIST.AMS.100-18.pdf
- NIST.AMS.100-2.pdf
- NIST.AMS.100-34.pdf

## Implementation checkpoint - page extraction and metadata

**Open in `src/extract_text.py`:** `extract_document()`.

**Input:** one PDF path. **Output:** page dictionaries and a diagnostic report.

**Key implementation:** `PdfReader` extracts each page; `enumerate(..., start=1)` preserves human-readable PDF page numbers; both `raw_text` and `cleaned_text` are retained.

**You should be able to explain:** citation metadata must be captured during ingestion. It cannot be reconstructed reliably after text from multiple pages has been mixed.

## Inspect direct extraction

`pypdf` reads the embedded text layer. This is faster and generally more accurate than OCR when a PDF was digitally generated. We begin with one document and inspect its page-level extraction.

In [2]:
sample_pdf = raw_dir / 'NIST.AMS.100-34.pdf'
reader = PdfReader(sample_pdf)
raw_pages = [(page.extract_text() or '') for page in reader.pages]

page_statistics = pd.DataFrame({
    'pdf_page': range(1, len(raw_pages) + 1),
    'raw_characters': [len(text.strip()) for text in raw_pages],
    'replacement_characters': [text.count('\ufffd') for text in raw_pages],
})

display(page_statistics.describe())
display(page_statistics.head())

        pdf_page  raw_characters  replacement_characters
count  52.000000       52.000000                    52.0
mean   26.500000     2237.250000                     0.0
std    15.154757     1016.791105                     0.0
min     1.000000      278.000000                     0.0
25%    13.750000     1795.500000                     0.0
50%    26.500000     2271.500000                     0.0
75%    39.250000     2973.250000                     0.0
max    52.000000     4012.000000                     0.0

   pdf_page  raw_characters  replacement_characters
0         1             283                       0
1         2             583                       0
2         3             668                       0
3         4            2579                       0
4         5            4012                       0

## Detect repeated headers and footers

The extraction module examines the first and last five non-empty lines of each page. A short edge line appearing on at least 30% of populated pages is treated as repeated page furniture. This avoids manually hard-coding every document header.

In [3]:
repeated_lines = find_repeated_edge_lines(raw_pages)
print('Repeated edge lines detected:')
for line in sorted(repeated_lines):
    print('-', line)

Repeated edge lines detected:
- This publication is available free of charge from: https://doi.org/10.6028/NIST.AMS.100-34

## Compare raw and cleaned text

Cleaning removes repeated page furniture, isolated page numbers, and unnecessary whitespace. It also repairs words split across line boundaries, such as `manufac-\nturing`.

In [4]:
sample_page_number = 16
sample_raw_text = raw_pages[sample_page_number - 1]
sample_cleaned_text = clean_page_text(sample_raw_text, repeated_lines)

print('RAW TEXT (first 1,200 characters)')
print('-' * 80)
print(sample_raw_text[:1200])
print('\nCLEANED TEXT (first 1,200 characters)')
print('-' * 80)
print(sample_cleaned_text[:1200])

RAW TEXT (first 1,200 characters)
--------------------------------------------------------------------------------


10
This publication is available free of charge from: https://doi.org/10.6028/NIST.AMS.100-34

necessary PM, this excess can lead to wasted money in unnecessary labor hours and
materials. PM is planned downtime which is still downtime. The more time a piece of
equipment is down, the less opportunity there is for it to be operating to produce a product
or perform a process to support the organization’s revenue stream.

An organization typically designs the PM strategy to be a tradeoff between the potential
for excess maintenance and the risk of not doing enoug h maintenance thereby increasing
the presence of a fault and failure lead ing to RM. The potential for excess maintenance
leading to excess cost is also balanced with the invested cost of a Predictive Maintenance
strategy, discussed in detail in section 2.3.
2.3. Predictive Maintenance
Predictive Maintenance (PdM) is a strategy that dictates maintenance activities based upon
measures of reliability and/or condition. Reliability -centered maintenance (RCM) and
condition-based maintenance (CBM) are under the PdM strategy umbrella. Reliability and
condition can be measured at the physical level of a piece of

CLEANED TEXT (first 1,200 characters)
--------------------------------------------------------------------------------
necessary PM, this excess can lead to wasted money in unnecessary labor hours and materials. PM is planned downtime which is still downtime. The more time a piece of equipment is down, the less opportunity there is for it to be operating to produce a product or perform a process to support the organization’s revenue stream.
An organization typically designs the PM strategy to be a tradeoff between the potential for excess maintenance and the risk of not doing enoug h maintenance thereby increasing the presence of a fault and failure lead ing to RM. The potential for excess maintenance leading to excess cost is also balanced with the invested cost of a Predictive Maintenance strategy, discussed in detail in section 2.3.
2.3. Predictive Maintenance
Predictive Maintenance (PdM) is a strategy that dictates maintenance activities based upon measures of reliability and/or condition. Reliability -centered maintenance (RCM) and condition-based maintenance (CBM) are under the PdM strategy umbrella. Reliability and condition can be measured at the physical level of a piece of manufacturing equipment, workcell, assembly line, etc. and can also be measured at the functional level of a manufact

## Extract the complete corpus

Each retained page becomes one JSON object containing its source document, PDF page number, raw text, cleaned text, and character count. Pages with fewer than 30 useful characters are skipped and recorded in the diagnostic report.

In [5]:
pages_file = processed_dir / 'pages.jsonl'
report_file = processed_dir / 'extraction_report.json'

extract_corpus(raw_dir, pages_file, report_file)

Processed 3 documents
Retained 159 pages
Wrote page corpus to <USER_HOME>\Documents\ChatGPT\Data Analytics\engineering-document-rag-assistant\data\processed\pages.jsonl
Wrote extraction report to <USER_HOME>\Documents\ChatGPT\Data Analytics\engineering-document-rag-assistant\data\processed\extraction_report.json

## Inspect the processed page records

JSONL stores one independent JSON object per line. This makes the corpus easy to inspect, stream, and load into Pandas or Hugging Face Datasets.

In [6]:
records = [
    json.loads(line)
    for line in pages_file.read_text(encoding='utf-8').splitlines()
]
pages_df = pd.DataFrame(records)

print(f'Retained page records: {len(pages_df)}')
display(
    pages_df.groupby('document')
    .agg(
        retained_pages=('pdf_page', 'count'),
        median_cleaned_characters=('cleaned_character_count', 'median'),
        minimum_cleaned_characters=('cleaned_character_count', 'min'),
    )
)
display(pages_df[['document', 'pdf_page', 'cleaned_character_count']].head())

Retained page records: 159

,retained_pages,median_cleaned_characters,minimum_cleaned_characters
document,,,
NIST.AMS.100-18,43,2269.0,137
NIST.AMS.100-2,64,2783.0,384
NIST.AMS.100-34,52,2125.5,179

          document  pdf_page  cleaned_character_count
0  NIST.AMS.100-18         1                      137
1  NIST.AMS.100-18         2                      391
2  NIST.AMS.100-18         3                      737
3  NIST.AMS.100-18         5                     2269
4  NIST.AMS.100-18         6                     1937

In [7]:
report = json.loads(report_file.read_text(encoding='utf-8'))
report_rows = [
    {
        'document': item['document'],
        'total_pdf_pages': item['total_pdf_pages'],
        'retained_pages': item['retained_pages'],
        'skipped_pages': item['skipped_pages'],
        'replacement_characters': item['replacement_characters_in_raw_text'],
    }
    for item in report['documents']
]
display(pd.DataFrame(report_rows))

,document,total_pdf_pages,retained_pages,skipped_pages,replacement_characters
0,NIST.AMS.100-18,45,43,"[4, 38]",0
1,NIST.AMS.100-2,66,64,"[2, 4]",0
2,NIST.AMS.100-34,52,52,[],0

## Where the extracted text is stored

The source PDFs remain unchanged in `data/raw/`. The extraction pipeline writes two files into `data/processed/`:

- `pages.jsonl`: one page record per line, including raw text, cleaned text, document name, and PDF page number
- `extraction_report.json`: document-level diagnostics, including retained pages, skipped pages, and repeated lines removed

The notebook can safely rerun extraction because these files are reproducible outputs of the source PDFs and cleaning code.

In [8]:
print('Page corpus:', pages_file.resolve())
print('Exists:', pages_file.exists(), '| Size:', f'{pages_file.stat().st_size / 1024:.1f} KB')
print('Extraction report:', report_file.resolve())
print('Exists:', report_file.exists(), '| Size:', f'{report_file.stat().st_size / 1024:.1f} KB')

example_record = records[10]
print('\nExample stored record (text shortened for display):')
print({
    'document': example_record['document'],
    'filename': example_record['filename'],
    'pdf_page': example_record['pdf_page'],
    'raw_text_preview': example_record['raw_text'][:180],
    'cleaned_text_preview': example_record['cleaned_text'][:180],
    'cleaned_character_count': example_record['cleaned_character_count'],
})

Page corpus: <USER_HOME>\Documents\ChatGPT\Data Analytics\engineering-document-rag-assistant\data\processed\pages.jsonl
Exists: True | Size: 794.0 KB
Extraction report: <USER_HOME>\Documents\ChatGPT\Data Analytics\engineering-document-rag-assistant\data\processed\extraction_report.json
Exists: True | Size: 1.5 KB

Example stored record (text shortened for display):
{'document': 'NIST.AMS.100-18', 'filename': 'NIST.AMS.100-18.pdf', 'pdf_page': 12, 'raw_text_preview': 'This publication is available free of charge from: https://doi.org/10.6028/NIST.AMS.100-18 \nmaintenance staff with spare parts being another 32 %, as seen in Figure 2.1. Komonen es', 'cleaned_text_preview': 'maintenance staff with spare parts being another 32 %, as seen in Figure 2.1. Komonen estimates that industrial maintenance is 5.5 % of company turnover (i.e., sales); however, it ', 'cleaned_character_count': 2443}

## Cleaning process, step by step

For each document, the pipeline performs the following operations:

1. Open the PDF with `PdfReader`.
2. Extract every page's embedded text. If extraction returns `None`, use an empty string.
3. Inspect the first and last five non-empty lines of every populated page.
4. Count repeated edge lines. A line found on at least 30% of pages is treated as a header or footer.
5. Process each page line by line.
6. Normalize repeated whitespace to one space.
7. Remove detected headers, DOI running lines, empty lines, and isolated page numbers.
8. Repair words hyphenated across a line break, such as `manufac-\nturing`.
9. Join ordinary wrapped lines while retaining useful structural line breaks.
10. Skip a page if fewer than 30 useful characters remain.
11. Save both raw and cleaned text with source-page metadata.

The raw version is deliberately retained. If a cleaning rule damages text, we can compare the two versions and rebuild the corpus without returning to OCR.

In [9]:
import inspect

print('The cleaning function used by the notebook and reusable pipeline:')
print(inspect.getsource(clean_page_text))

The cleaning function used by the notebook and reusable pipeline:
def clean_page_text(raw_text: str, repeated_lines: set[str]) -> str:
    """Remove page furniture and normalize PDF line wrapping."""
    retained_lines: list[str] = []

    for raw_line in raw_text.splitlines():
        line = normalize_line(raw_line)
        if not line or line in repeated_lines:
            continue

        # This running header is common in the selected NIST publications.
        if line.lower().startswith("this publication is available free of charge from:"):
            continue

        # Remove isolated PDF page numbers while retaining numbers in prose.
        if re.fullmatch(r"\d{1,3}", line):
            continue

        retained_lines.append(line)

    text = "\n".join(retained_lines)

    # Repair words split across PDF line boundaries, e.g. "manufac-\nturing".
    text = re.sub(r"(?<=[A-Za-z])[-‐]\n(?=[a-z])", "", text)

    # Join ordinary wrapped lines while retaining likely headings and list items.
    text = re.sub(r"(?<![.!?:;])\n(?=[a-z(])", " ", text)
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()

## Manual quality inspection

Automated checks catch missing data and repeated headers, but they cannot determine whether prose, lists, or tables remain readable. We therefore inspect a fixed random sample and one known page. A fixed `random_state` makes the sample reproducible.

In [10]:
pd.set_option('display.max_colwidth', 1000)

quality_sample = pages_df.sample(5, random_state=42)
for _, row in quality_sample.iterrows():
    print('=' * 100)
    print(f"Document: {row['document']} | PDF page: {row['pdf_page']}")
    print('-' * 100)
    print(row['cleaned_text'][:1500])
    print()

known_example = pages_df[
    (pages_df['document'] == 'NIST.AMS.100-34')
    & (pages_df['pdf_page'] == 16)
].iloc[0]

print('=' * 100)
print('Known extraction-artifact example: NIST.AMS.100-34, PDF page 16')
print('-' * 100)
print(known_example['cleaned_text'][:1800])

====================================================================================================
Document: NIST.AMS.100-2 | PDF page: 38
----------------------------------------------------------------------------------------------------
Barriers: Current status of the PHM framework in various industries is unclear; a PHM framework that includes standards is lacking, leading to inconsistencies in performance assessment.
Approach: The development of the framework would involve: 1) performing a benchmark for current state, 2) cataloging
Key Performance Indicators (KPIs), and 3) defining PHM standard architecture and traceability. A standard framework will provide consistency in assessment of PHM performance and support new standards development.
FIGURE 3-1. OVERARCHING ARCHITECTURE FRAMEWORK FOR PHM
WITH STANDARDS AND KPIS
Roadmap Action Plan
Targets/ Capabilities
Milestones
1-2 years w Benchmark the current state of machine monitoring in select industries, such as oil and gas, automotive, aerospace, and pharma/medical w Identification of two key PHM scenarios to benchmark from each industry, non-advanced and advanced w 80% of the benchmarks completed
3-5 years w Catalog the KPIs in the above industries and map-out common trends for prognostics and diagnostics w Catalog of KPIs based on benchmarking and best practices w Published catalog that is accepted by 30% of industry
5+ years w Define the standard PHM architecture w Create methods for asset traceability and history recording w Published system architecture and data flow w Playbook for machine monitoring/benchmarking w ISO standard traceability w Creation of ISO documents
Stakeholders & Potential
Roles
PHM Users Champion needs, problems, current state
PHM

====================================================================================================
Document: NIST.AMS.100-34 | PDF page: 49
----------------------------------------------------------------------------------------------------
Tuovila, Alicia. 2019. “Inventory Carrying Cost.” https://www.investopedia.com/terms/c/carryingcostofinventory.asp
U.S. Census Bureau. (2020). Annual Survey of Manufactures.
https://www.census.gov/programs-surveys/asm.html
U.S. Census Bureau. (2020). County Business Patterns.
https://www.census.gov/programs-surveys/cbp.html
U.S. Census Bureau. (2020). Economic Census. https://www.census.gov/programssurveys/economic-census.html
Wasp Barcode Technologies. 2020. “The Real Cost of Carrying Inventory.” http://www.waspbarcode.com/buzz/real-cost-carrying-inventory

====================================================================================================
Document: NIST.AMS.100-34 | PDF page: 22
----------------------------------------------------------------------------------------------------
Maintenance Costs and Associated Inventory Costs
Direct maintenance and repair costs include the cost of labor and materials along with cascading effects, which refers to subsequent damage caused by a breakdown of a machine (e.g., repair). Section 4.1 discusses direct maintenance costs and Section 4.2 presents subsequent damage. Costs due to increased inventory due to uncertainty from maintenance issues is discussed in Section 4.3.
4.1. Direct Maintenance Costs
Two general methods are used to estimate direct maintenance costs (e.g., maintenance department expenditures). The first utilizes survey responses to the following topics:
• Establishment size (Question 1)
• Payroll (Question 2)
• Shipments (Question 4)
• NAICS codes (Question 5)
• Maintenance and repair (Question 6)
The responses are scaled-up using industry data on payroll or shipments. Additionally, post stratification by industry and employment size can be used, where portions of the data are each scaled. The s caling would match the company size and industry corresponding to national data:
Equation 3
𝐷𝑀𝐶 = ∑ ∑ (𝐸𝑀𝑥,𝑠,𝑖
𝑆𝑀𝑥,𝑠,𝑖
𝑆𝑀𝑇𝑂𝑇,𝑠,𝑖)
𝑆
𝑠=1
𝐼
𝑖=1 where
𝐷𝑀𝐶 = Direct maintenance costs
𝐸𝑀𝑥,𝑠,𝑖 = Estimate of mainten ance costs for establishment x with strata size s within industry strata i
𝑆𝑀𝑥,𝑠,𝑖 = Scaling metric from establishment 𝑥, which is either total payroll or shipments (depending on the method used) for industry i with size s
𝑆𝑀𝑇𝑂𝑇,𝑠,𝑖 = Total payroll or shipments (depending on the method used) for industr

====================================================================================================
Document: NIST.AMS.100-2 | PDF page: 15
----------------------------------------------------------------------------------------------------
 Health Management of Smart Manufacturing Systems:
Al Salour, Senior Technical Fellow, The Boeing Company
Boeing experience with implementing prognostics and health management systems into their manufacturing processes: Common standards and interoperability between systems will benefit software-assisted diagnosis and prognosis. This is a challenge in a large organization because business units have their own preferences and have even created unique software. One of the main issues currently faced is the amount of time it takes to direct data towards a decision. A lot of data is collected, yet current technology doesn’t provide enough actionable information.
Emerging tools and advancements are improving software-assisted diagnosis and prognosis to provide more actionable information and facilitate quicker decision-making.
 Day 2 – Opening Remarks
Albert Wavering, Chief, Intelligent Systems Division (ISD), EL, NIST
Advances in intelligent manufacturing: The Intelligent Systems Division develops and advances measurement science and standards to speed development, adoption, and integration of leading-edge intelligent technologies that will improve U.S. manufacturing performance. A key aspect of ISD’s work is enabling real-time monitoring, control, and performance optimization of smart manufacturing. The Internet of Things combined with cyber-physical systems (highly networked information technology/IT and physical systems) has the potential to change the face of manufacturing.

====================================================================================================
Document: NIST.AMS.100-2 | PDF page: 54
----------------------------------------------------------------------------------------------------
Barriers: Inability to make good decisions based on data; wrong information and detail at the wrong level.
Approach: The approach involves developing the appropriate information at each level to facilitate key operations and maintenance decisions. The outcome is a traffic light approach to data (green, yellow, red) for actionable decisions.
FIGURE 4-4. PHM INFRASTRUCTURE TO DELIVER RELEVANT,
TIMELY INFORMATION
Stakeholders & Potential
Roles
PHM Users
Provide inputs for ERP and rules for actionable decisions
PHM Providers/
Tech Developers
Develop models of selected equipment;
disparate data fusion
Technology
Integrators
Integrate PHM decisions with ERP
Academia Develop cyber algorithms and models
Standards
Committees
Develop metrics for decision success
Government Support development efforts
Benefits / Impacts
Impact Benefit
High Improves reliability/reduces failures: Better data for prevention
High Reduces costs: Reduced failures
Medium Accelerates innovation:
Innovations in PHM methods
Medium Enhances industry competiveness: Reduces costs, provides agility
High Speeds process reconfigurability: The right data is used to make quick decisions
High Improves maintenance scheduling: Improved decision making in real-time
Relative Success Factors
Time to Achieve
Results Medium
Relative Cost of R&D Medium
Complexity of R&D Medium
Risk Associated with
R&D Low
Likelihood of
Success/Adoption High
Roadmap Action Plan
Targets/ Capabilities
Milestones
1-2 years w Develop tools to build “t

====================================================================================================
Known extraction-artifact example: NIST.AMS.100-34, PDF page 16
----------------------------------------------------------------------------------------------------
necessary PM, this excess can lead to wasted money in unnecessary labor hours and materials. PM is planned downtime which is still downtime. The more time a piece of equipment is down, the less opportunity there is for it to be operating to produce a product or perform a process to support the organization’s revenue stream.
An organization typically designs the PM strategy to be a tradeoff between the potential for excess maintenance and the risk of not doing enoug h maintenance thereby increasing the presence of a fault and failure lead ing to RM. The potential for excess maintenance leading to excess cost is also balanced with the invested cost of a Predictive Maintenance strategy, discussed in detail in section 2.3.
2.3. Predictive Maintenance
Predictive Maintenance (PdM) is a strategy that dictates maintenance activities based upon measures of reliability and/or condition. Reliability -centered maintenance (RCM) and condition-based maintenance (CBM) are under the PdM strategy umbrella. Reliability and condition can be measured at the physical level of a piece of manufacturing equipment, workcell, assembly line, etc. and can also be measured at the functional level of a manufacturing process. Measurements are often obtained through sensor data and can be paired with historical data and models to ascertain existing reliability or conditions.
Depending upon the availability of data and/or model richness, future reliability or conditions can be forecast. Regardless of the prediction of a future state, a manufacturers’ awareness of current reliability and conditions offers them critical insight to plan maintenance activities.
A key benefit of PdM is that maintenance is timelier and less likely to be unnecessary and excessive as compared to PM. Since PdM maintenance is us

## Why NLTK is not required here

NLTK is useful for many traditional NLP workflows, but it is not required by RAG. For this project we will use lightweight sentence-boundary rules plus the Hugging Face tokenizer used by the embedding model. This keeps chunk length aligned with the transformer's actual token limits.

We will **not** remove stop words or stem the corpus before embedding. Transformer embedding models use word order and surrounding context; changing `the bearing is not damaged` into something like `bear damag` can remove negation and reduce meaning. We therefore preserve natural text.

## Chunking-readiness audit

Before chunking, we verify structural integrity and quantify remaining extraction artifacts. A corpus is ready for initial chunking when records are complete, source-page metadata is unique, text is non-empty, decoding is clean, and repeated page furniture has been removed. Minor isolated spacing artifacts can be documented and revisited if retrieval tests show an effect.

In [11]:
from collections import Counter
import re

required_fields = {
    'document', 'filename', 'pdf_page', 'raw_text',
    'cleaned_text', 'cleaned_character_count'
}
page_keys = list(zip(pages_df['document'], pages_df['pdf_page']))

readiness = {
    'records': len(pages_df),
    'documents': pages_df['document'].nunique(),
    'records_missing_fields': sum(bool(required_fields - set(record)) for record in records),
    'empty_cleaned_text': int(pages_df['cleaned_text'].str.strip().eq('').sum()),
    'duplicate_document_pages': sum(count > 1 for count in Counter(page_keys).values()),
    'character_count_mismatches': sum(
        len(record['cleaned_text']) != record['cleaned_character_count']
        for record in records
    ),
    'replacement_characters': int(pages_df['cleaned_text'].str.count('\ufffd').sum()),
    'leftover_running_headers': int(
        pages_df['cleaned_text'].str.contains(
            'This publication is available free of charge from:',
            regex=False,
        ).sum()
    ),
    'pages_with_known_split_words': int(
        pages_df['cleaned_text'].str.contains(r'\b(?:enoug h|lead ing)\b', regex=True).sum()
    ),
    'pages_with_space_before_hyphen': int(
        pages_df['cleaned_text'].str.contains(r'\b[A-Za-z]{3,}\s+-[A-Za-z]{2,}\b', regex=True).sum()
    ),
}

display(pd.DataFrame([readiness]).T.rename(columns={0: 'value'}))

blocking_failures = [
    name for name in (
        'records_missing_fields', 'empty_cleaned_text',
        'duplicate_document_pages', 'character_count_mismatches',
        'replacement_characters', 'leftover_running_headers',
    )
    if readiness[name] != 0
]

print('Decision:', 'NOT READY' if blocking_failures else 'READY FOR INITIAL CHUNKING')
print('Blocking failures:', blocking_failures or 'None')
print('Non-blocking limitation: isolated spacing artifacts remain and will be monitored during retrieval evaluation.')

                                value
records                           159
documents                           3
records_missing_fields              0
empty_cleaned_text                  0
duplicate_document_pages            0
character_count_mismatches          0
replacement_characters              0
leftover_running_headers            0
pages_with_known_split_words        1
pages_with_space_before_hyphen      9

Decision: READY FOR INITIAL CHUNKING
Blocking failures: None
Non-blocking limitation: isolated spacing artifacts remain and will be monitored during retrieval evaluation.

## Validation checks

Assertions make assumptions executable. If an assumption stops being true after a code or corpus change, the notebook raises an error instead of silently producing poor data.

In [12]:
assert len(pages_df) == 159, 'Unexpected retained-page count'
assert pages_df['document'].nunique() == 3, 'Expected three source documents'
assert (pages_df['cleaned_character_count'] >= 30).all()
assert pages_df['cleaned_text'].str.contains('This publication is available free of charge from:', regex=False).sum() == 0
assert pages_df['raw_text'].str.count('\ufffd').sum() == 0

print('All extraction validation checks passed.')

All extraction validation checks passed.

## What you should be able to explain

> I extracted the corpus at page level using pypdf, preserved source-page metadata for citations, retained raw text for traceability, removed repeated page furniture, repaired common line-wrapping artifacts, skipped visually blank pages, and stored the processed corpus as JSONL for downstream chunking.

## Before moving to chunking

Inspect several records containing normal prose, headings, lists, and tables. Write down any cleaning problems you observe. The next notebook will explain chunk size, overlap, metadata propagation, and retrieval trade-offs.

In [13]:
pd.set_option("display.max_colwidth", 1000)

sample = pages_df.sample(5, random_state=42)

for _, row in sample.iterrows():
    print("=" * 100)
    print(f"Document: {row['document']} | PDF page: {row['pdf_page']}")
    print("-" * 100)
    print(row["cleaned_text"][:2000])
    print()

====================================================================================================
Document: NIST.AMS.100-2 | PDF page: 38
----------------------------------------------------------------------------------------------------
Barriers: Current status of the PHM framework in various industries is unclear; a PHM framework that includes standards is lacking, leading to inconsistencies in performance assessment.
Approach: The development of the framework would involve: 1) performing a benchmark for current state, 2) cataloging
Key Performance Indicators (KPIs), and 3) defining PHM standard architecture and traceability. A standard framework will provide consistency in assessment of PHM performance and support new standards development.
FIGURE 3-1. OVERARCHING ARCHITECTURE FRAMEWORK FOR PHM
WITH STANDARDS AND KPIS
Roadmap Action Plan
Targets/ Capabilities
Milestones
1-2 years w Benchmark the current state of machine monitoring in select industries, such as oil and gas, automotive, aerospace, and pharma/medical w Identification of two key PHM scenarios to benchmark from each industry, non-advanced and advanced w 80% of the benchmarks completed
3-5 years w Catalog the KPIs in the above industries and map-out common trends for prognostics and diagnostics w Catalog of KPIs based on benchmarking and best practices w Published catalog that is accepted by 30% of industry
5+ years w Define the standard PHM architecture w Create methods for asset traceability and history recording w Published system architecture and data flow w Playbook for machine monitoring/benchmarking w ISO standard traceability w Creation of ISO documents
Stakeholders & Potential
Roles
PHM Users Champion needs, problems, current state
PHM Providers/
Tech Developers
Provide historical successes and current capabilities
Technology
Integrators
Adopt standard input on architecture
Academia Conduct literature studies, perform due diligence
Standards
Committees Accept and publish
Government Provide technical support
Benefits / Impacts
Impact Benefit
High Improves reliability/reduces failures
High Reduces costs
Medium Accelerates innovation
High Enhances industry competiveness
Low Speeds process reconfigurability
High Improves maintenan

====================================================================================================
Document: NIST.AMS.100-34 | PDF page: 49
----------------------------------------------------------------------------------------------------
Tuovila, Alicia. 2019. “Inventory Carrying Cost.” https://www.investopedia.com/terms/c/carryingcostofinventory.asp
U.S. Census Bureau. (2020). Annual Survey of Manufactures.
https://www.census.gov/programs-surveys/asm.html
U.S. Census Bureau. (2020). County Business Patterns.
https://www.census.gov/programs-surveys/cbp.html
U.S. Census Bureau. (2020). Economic Census. https://www.census.gov/programssurveys/economic-census.html
Wasp Barcode Technologies. 2020. “The Real Cost of Carrying Inventory.” http://www.waspbarcode.com/buzz/real-cost-carrying-inventory

====================================================================================================
Document: NIST.AMS.100-34 | PDF page: 22
----------------------------------------------------------------------------------------------------
Maintenance Costs and Associated Inventory Costs
Direct maintenance and repair costs include the cost of labor and materials along with cascading effects, which refers to subsequent damage caused by a breakdown of a machine (e.g., repair). Section 4.1 discusses direct maintenance costs and Section 4.2 presents subsequent damage. Costs due to increased inventory due to uncertainty from maintenance issues is discussed in Section 4.3.
4.1. Direct Maintenance Costs
Two general methods are used to estimate direct maintenance costs (e.g., maintenance department expenditures). The first utilizes survey responses to the following topics:
• Establishment size (Question 1)
• Payroll (Question 2)
• Shipments (Question 4)
• NAICS codes (Question 5)
• Maintenance and repair (Question 6)
The responses are scaled-up using industry data on payroll or shipments. Additionally, post stratification by industry and employment size can be used, where portions of the data are each scaled. The s caling would match the company size and industry corresponding to national data:
Equation 3
𝐷𝑀𝐶 = ∑ ∑ (𝐸𝑀𝑥,𝑠,𝑖
𝑆𝑀𝑥,𝑠,𝑖
𝑆𝑀𝑇𝑂𝑇,𝑠,𝑖)
𝑆
𝑠=1
𝐼
𝑖=1 where
𝐷𝑀𝐶 = Direct maintenance costs
𝐸𝑀𝑥,𝑠,𝑖 = Estimate of mainten ance costs for establishment x with strata size s within industry strata i
𝑆𝑀𝑥,𝑠,𝑖 = Scaling metric from establishment 𝑥, which is either total payroll or shipments (depending on the method used) for industry i with size s
𝑆𝑀𝑇𝑂𝑇,𝑠,𝑖 = Total payroll or shipments (depending on the method used) for industry i with size s, where 𝑇𝑂𝑇 indicates the total from either the Annual Survey of
Manufactures or the Economic Census
Three different stratifications for calculating estimates are utilized in this approach.
Stratification is used to address any over/under representation of any groups that could result in skewing estimates of costs. Manufacturers may experience different maintenance costs as a result of the types of products they are producing and the size of their establishment. If one group is ov

====================================================================================================
Document: NIST.AMS.100-2 | PDF page: 15
----------------------------------------------------------------------------------------------------
 Health Management of Smart Manufacturing Systems:
Al Salour, Senior Technical Fellow, The Boeing Company
Boeing experience with implementing prognostics and health management systems into their manufacturing processes: Common standards and interoperability between systems will benefit software-assisted diagnosis and prognosis. This is a challenge in a large organization because business units have their own preferences and have even created unique software. One of the main issues currently faced is the amount of time it takes to direct data towards a decision. A lot of data is collected, yet current technology doesn’t provide enough actionable information.
Emerging tools and advancements are improving software-assisted diagnosis and prognosis to provide more actionable information and facilitate quicker decision-making.
 Day 2 – Opening Remarks
Albert Wavering, Chief, Intelligent Systems Division (ISD), EL, NIST
Advances in intelligent manufacturing: The Intelligent Systems Division develops and advances measurement science and standards to speed development, adoption, and integration of leading-edge intelligent technologies that will improve U.S. manufacturing performance. A key aspect of ISD’s work is enabling real-time monitoring, control, and performance optimization of smart manufacturing. The Internet of Things combined with cyber-physical systems (highly networked information technology/IT and physical systems) has the potential to change the face of manufacturing. As the use of intelligent systems grows in this sector, new technologies and strategies for prognostics and health management will be needed to keep pace and to take advantage of new opportunities. This workshop is a good forum for gaining insights on how
PHM can adapt and advance in new smart manufacturing environments.
 Recent Advances and Transformation Direction of PHM:
Jay Lee, Professor at the University of Cincinnati, Founding Director of National Science
Foundation (NSF) Industry/ Unive

====================================================================================================
Document: NIST.AMS.100-2 | PDF page: 54
----------------------------------------------------------------------------------------------------
Barriers: Inability to make good decisions based on data; wrong information and detail at the wrong level.
Approach: The approach involves developing the appropriate information at each level to facilitate key operations and maintenance decisions. The outcome is a traffic light approach to data (green, yellow, red) for actionable decisions.
FIGURE 4-4. PHM INFRASTRUCTURE TO DELIVER RELEVANT,
TIMELY INFORMATION
Stakeholders & Potential
Roles
PHM Users
Provide inputs for ERP and rules for actionable decisions
PHM Providers/
Tech Developers
Develop models of selected equipment;
disparate data fusion
Technology
Integrators
Integrate PHM decisions with ERP
Academia Develop cyber algorithms and models
Standards
Committees
Develop metrics for decision success
Government Support development efforts
Benefits / Impacts
Impact Benefit
High Improves reliability/reduces failures: Better data for prevention
High Reduces costs: Reduced failures
Medium Accelerates innovation:
Innovations in PHM methods
Medium Enhances industry competiveness: Reduces costs, provides agility
High Speeds process reconfigurability: The right data is used to make quick decisions
High Improves maintenance scheduling: Improved decision making in real-time
Relative Success Factors
Time to Achieve
Results Medium
Relative Cost of R&D Medium
Complexity of R&D Medium
Risk Associated with
R&D Low
Likelihood of
Success/Adoption High
Roadmap Action Plan
Targets/ Capabilities
Milestones
1-2 years w Develop tools to build “twin” or cyber-models of line replaceable unit (LRU) parts/components to get RUL or mean time to failure (MTTF) predictions w Determine what data is needed to model diagnostics & prognostics w Conduct needs assessment to determine information needed at each operational level w Understand prognostic needs at each level of operation w Develop capability to fuse data from non-commensurate data sources for use in diagnosis and prognosis w Develop fusion methods for sensor data, information algorithms

In [14]:
record = pages_df[
    (pages_df["document"] == "NIST.AMS.100-34")
    & (pages_df["pdf_page"] == 16)
].iloc[0]

print(record["cleaned_text"])

necessary PM, this excess can lead to wasted money in unnecessary labor hours and materials. PM is planned downtime which is still downtime. The more time a piece of equipment is down, the less opportunity there is for it to be operating to produce a product or perform a process to support the organization’s revenue stream.
An organization typically designs the PM strategy to be a tradeoff between the potential for excess maintenance and the risk of not doing enoug h maintenance thereby increasing the presence of a fault and failure lead ing to RM. The potential for excess maintenance leading to excess cost is also balanced with the invested cost of a Predictive Maintenance strategy, discussed in detail in section 2.3.
2.3. Predictive Maintenance
Predictive Maintenance (PdM) is a strategy that dictates maintenance activities based upon measures of reliability and/or condition. Reliability -centered maintenance (RCM) and condition-based maintenance (CBM) are under the PdM strategy umbrella. Reliability and condition can be measured at the physical level of a piece of manufacturing equipment, workcell, assembly line, etc. and can also be measured at the functional level of a manufacturing process. Measurements are often obtained through sensor data and can be paired with historical data and models to ascertain existing reliability or conditions.
Depending upon the availability of data and/or model richness, future reliability or conditions can be forecast. Regardless of the prediction of a future state, a manufacturers’ awareness of current reliability and conditions offers them critical insight to plan maintenance activities.
A key benefit of PdM is that maintenance is timelier and less likely to be unnecessary and excessive as compared to PM. Since PdM maintenance is usually performed less frequently than PM maintenance, there is less equipment downtime allowing for more revenue - generating manufacturing operations. One downside to PdM is that it usually requires a larger upfront investment by the manufacturer as compared to PM. The manufacturer needs to determine exactly what and how they want to monitor. They need to determine what measurements will signal the need for maintenance activities. A financial investment is required to procure and integrate the appropriate hardware and software to capture and analyze the necessary data. Often a workforce investment is required to train personnel on what measures should be monitored, how data should be analyzed, and responses in the presence of specific triggers. Recognizing the advantages and disadvantages of PdM, most manufacturers seek to optimize between PM and PdM while minimizing RM. It is unlikely that manufacturers will maintain the same maintenance strategy paradigm throughout the life of their operati on g iven changing manufacturing equipment and processes, the evolution of sensing and monitoring technology, the increased affordability of computing power and data storage , the expanded capability of software algorithms to monitor and predict future health states, and the possible reconfigurations of assembly lines to produce new or custom products. Manufacturers, particularly those that want to remain competitive on the global stage, should strategically look to advance their maintenance strategies to maximize equipment uptime and maintain necessary part quality and productive targets.